Base Header Level: 2
latex author: $AUTHOR
latex title: $TITLE
bibtex: $MYBIB
my abstract: $ABSTRACT
myacknowledgments: $ACKNOWLEDGMENTS
latex input: $TEMPLATE/setup.tex
latex footer: $TEMPLATE/footer.tex
