Base Header Level: 2
latex author: $AUTHOR
latex title: $TITLE
bibtex: $BIBTEX
my abstract: $ABSTRACT
my acknowledgments: $ACKNOWLEDGMENTS
my packages: $PACKAGES
latex input: $TEMPLATE/setup.tex
latex footer: $TEMPLATE/footer.tex
